### PR TITLE
Fix: gif image for node-mongo CLI readme and doc shows outdated content, API boilerplate template should also have a .gif image that shows how to run it 

### LINKED ISSUE #36: .gif image for node-mongo CLI readme and doc shows outdated content, API boilerplate template should also have a .gif image that shows how to run it
#### Videos
- CLI: https://app.claap.io/code-collabo/docs-issue-2a-gif-image-for-node-mongo-cli-readme-and-doc-shows-outdated-content-c-k_zUmfU3ae-hGNvBh3RSf06
- API bolerplate templates: https://app.claap.io/code-collabo/docs-issue-2b-node-mongo-api-template-should-also-have-a-gif-image-that-shows-how-to-run-it-c-k_zUmfU3ae-fyVgj0A8-5vG

### PR DESCRIPTION
**Pull request by KamiNation**
**This pull request makes the following changes**
* Fixes code-collabo/.github#36

**General checklist**
- [x] File or folder now contains changes as specified in the issue i worked on
- [x] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**

Replace this text with the testing checklist from the issue this pull request fixes.

Ping @code-collabo/docs

### CODE REVIEW

**Review by Ifycode — CHANGES_REQUESTED** [review]
@KamiNation Link your issue to your pull request, so that I can approve your PR.

**Comment by KamiNation** [comment]
@Ifycode Ma'am. If i get you correctly, you mean i should add a link that refers to where the issue was originally issued right? 

Which i did by adding a link above. If i am mistaken pls let me know. 

Thank you.

**Comment by Ifycode** [comment]
@KamiNation I saw you changing a lot of things in your [comment](https://github.com/code-collabo/node-mongo/pull/48#issue-1729679030). Please always ask me if you do not understand anything. I will gladly explain.

Ticking the general checklist is correct 👍🏼

Apart from the general checklist, the only thing you should be changing are: 

1. Linking issue to PR: 
````
* Fixes code-collabo/put-repo-name-where-the-issue-is-located-here#putTheIssueNumberHere 
````

This is what you should change it to based on the instruction in that line (put-repo-name-where-the-issue-is-located-here & putTheIssueNumberHere) :
````
* Fixes code-collabo/.github#36
````
Once you change it in that manner, this will be the outcome:
* Fixes code-collabo/.github#36

That is how you link an issue to a PR. 

2. Testing checklist: You shouldn't be touching that area at all for now. I will let you know when you need it.

As for any other thing in there @ping etc, leave those ones too. If you feel there is a problem there, let me know. We can then change it from the source.

**Review by Ifycode — CHANGES_REQUESTED** [review]
I've restored the [comment/description](https://github.com/code-collabo/node-mongo/pull/48#issue-1729679030) back to initial. What to do for me before I approve your PR:
- Link your issue to your PR - I showed how to so that in [my previous review comment](https://github.com/code-collabo/node-mongo/pull/48#issuecomment-1574659806)
- Remove`#10` from your PR title
@KamiNation

**Comment by KamiNation** [comment]
> I've restored the [comment/description](https://github.com/code-collabo/node-mongo/pull/48#issue-1729679030) back to initial. What to do for me before I approve your PR:
> 
> * Link your issue to your PR - I showed how to so that in [my previous review comment](https://github.com/code-collabo/node-mongo/pull/48#issuecomment-1574659806)
> * Remove`#10` from your PR title
>   @KamiNation

I have done that ma, thanks a lot. I really appreciate

**Review by Ifycode — APPROVED** [review]
Approved 👍🏼

**Comment by KamiNation** [comment]
> Approved 👍🏼

Okay. Thank you.

**Pull request closed without merging**
